token = "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOiIwMDAwMDAiLCJ1c2VyX25hbWUiOiJyb2NrIiwicmVhbF9uYW1lIjoi5ZC05Lit5Y2JIiwiYXZhdGFyIjoiIiwiYXV0aG9yaXRpZXMiOlsiYWRtaW5pc3RyYXRvciJdLCJjbGllbnRfaWQiOiJzYWJlciIsInJvbGVfbmFtZSI6ImFkbWluaXN0cmF0b3IiLCJsaWNlbnNlIjoicG93ZXJlZCBieSBibGFkZXgiLCJwb3N0X2lkIjoiMTEyMzU5ODgxNzczODY3NTIwMSIsInVzZXJfaWQiOiIxNjM4NDQwMzA3ODU0NDc1MjY1Iiwicm9sZV9pZCI6IjExMjM1OTg4MTY3Mzg2NzUyMDEiLCJzY29wZSI6WyJhbGwiXSwibmlja19uYW1lIjoi5ZC05Lit5Y2JIiwib2F1dGhfaWQiOiIiLCJkZXRhaWwiOnsidGVuYW50TmFtZSI6IuWIhuS5kOayueermSJ9LCJleHAiOjE3MDY5MzkwMzAsImRlcHRfaWQiOiIxMTIzNTk4ODEzNzM4Njc1MjAxIiwianRpIjoiNTNkZGRiNjEtZjEyMC00YzRkLWJmMTYtMDk4YWI4OGJlM2UzIiwiYWNjb3VudCI6InJvY2sifQ.1I4W0ZU0fzq9CGJq3jg6JGI58fTz2X7Qig_-VJ_GeXI"
Authorization = "cPlKOmRGQgeESow6P1D1P58WDuBvA/vMtT+IpWTf/H2Ye0yK8mHVwRqMd9OEPO+0A1JNJ3DLAtoVthHCCrC4TaWbqCFSeAg3eqsKzfrafqpGTu0scOHM8UYekyo3JHNO4SvKBFxm2KHQ1oRY5WNwUPIbrLeXo+SDAxPJ5yiRBgE="
headers = {
        'Authorization': Authorization,
        'Blade-Auth': token,
        'Content-Type': 'application/json'
        }
testhost = "https://5r5152q357.goho.co/right/api"
onlinehost = "https://right.rayoservice.com/api"