token = 'bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOiIwMDAwMDAiLCJ1c2VyX25hbWUiOiJyb2NrIiwicmVhbF9uYW1lIjoi5ZC05Lit5Y2JIiwiYXZhdGFyIjoiIiwiYXV0aG9yaXRpZXMiOlsiYWRtaW5pc3RyYXRvciJdLCJjbGllbnRfaWQiOiJzYWJlciIsInJvbGVfbmFtZSI6ImFkbWluaXN0cmF0b3IiLCJsaWNlbnNlIjoicG93ZXJlZCBieSBibGFkZXgiLCJwb3N0X2lkIjoiMTEyMzU5ODgxNzczODY3NTIwMSIsInVzZXJfaWQiOiIxNjM4NDQwMzA3ODU0NDc1MjY1Iiwicm9sZV9pZCI6IjExMjM1OTg4MTY3Mzg2NzUyMDEiLCJzY29wZSI6WyJhbGwiXSwibmlja19uYW1lIjoi5ZC05Lit5Y2JIiwib2F1dGhfaWQiOiIiLCJkZXRhaWwiOnsidGVuYW50TmFtZSI6IuWIhuS5kOayueermSJ9LCJleHAiOjE2ODM1MTIyNTQsImRlcHRfaWQiOiIxMTIzNTk4ODEzNzM4Njc1MjAxIiwianRpIjoiMmEwYzJlOTUtMTVmNy00ODljLWI2YjMtZTVkNjAwNTVkYzcxIiwiYWNjb3VudCI6InJvY2sifQ.k4nJXKS8vp2m1Rk0jvyBGjC3ks2jId5BVlpjeUiWgOY'
Authorization = 'i6cflAXCsENcWi9HroyWP1mVKUsKU1kybsM81AIaP8q1BxnoUhiBQkvgwo5K5KuhdXfAb+yo6CfZVtrLnkG1rK9L363B/VOWmmzC96GF2qrNeFivNT9mmgdAVThzj/VHPnfdBbsH4IA7hsw1djKUMuqtszS5HzErdo0m4YiNBDY='
headers = {
        'Authorization': Authorization,
        'Blade-Auth': token,
        'Content-Type': 'application/json'
        }
testhost = "https://5r5152q357.goho.co/right/api"
onlinehost = "https://right.rayoservice.com/api"